### ISSUE TITLE
Bug: Invalid regular expression

### ISSUE THREAD

**Issue by jimmiejackson414** [kalimahapps/eslint-plugin-tailwind#5]
I love this plugin and how powerful it is. For some reason lately I've noticed that I am receiving an error which prevents me from restarting/starting the server though.

```
 ERROR  Cannot start nuxt:  Invalid regular expression: /^(|-)*([A-Za-z]+:)+[/: Unterminated character class                                                                                 10:24:31 AM
Occurred while linting /Users/jimmiejackson/Documents/repositories/test/components/common/Header.vue:113
Rule: "@kalimahapps/tailwind/sort"

  Occurred while linting components/common/Header.vue:113
  Rule: "@kalimahapps/tailwind/sort"
  at formatError (node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
  at Context.error (node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
  at Context.buildStart (node_modules/vite-plugin-eslint/dist/index.mjs:1:1766)
  at async Promise.all (index 8)
  at async hookParallel (node_modules/vite/dist/node/chunks/dep-df561101.js:43858:9)
  at async Object.buildStart (node_modules/vite/dist/node/chunks/dep-df561101.js:44182:13)
  at async node_modules/vite/dist/node/chunks/dep-df561101.js:65230:13
  at async _createServer (node_modules/vite/dist/node/chunks/dep-df561101.js:65260:9)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.d6a45f81.mjs:582:24)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.d6a45f81.mjs:1461:3)
```
What might cause this issue?

**Comment by abdul-alhasany** [comment]
Can you please provide a sample code? My guess is that you are using a class with a special character  which is breaking the regex.

**Comment by jimmiejackson414** [comment]
Sure thing. It appears to be coming from somewhere in this component:

```vue
<template>
  <header class="relative flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full bg-primary-black py-4">
    <nav
      class="w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between lg:px-24 py-14"
      aria-label="Global">
      <div class="flex items-center justify-between">
        <a
          class="flex-none text-xl font-semibold"
          href="/">
          <IconLogo class="h-14 w-auto" />
        </a>
        <div class="sm:hidden">
          <button
            type="button"
            class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800"
            data-hs-collapse="#navbar-with-mega-menu"
            aria-controls="navbar-with-mega-menu"
            aria-label="Toggle navigation">
            <svg
              class="hs-collapse-open:hidden w-4 h-4"
              width="16"
              height="16"
              fill="currentColor"
              viewBox="0 0 16 16">
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
            </svg>
            <svg
              class="hs-collapse-open:block hidden w-4 h-4"
              width="16"
              height="16"
              fill="currentColor"
              viewBox="0 0 16 16">
              <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
            </svg>
          </button>
        </div>
      </div>
      <div
        id="navbar-with-mega-menu"
        class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
        <div class="flex flex-col gap-5 mt-5 sm:flex-row sm:items-center sm:justify-end sm:mt-0 sm:pl-5">
          <span
            v-for="link in navigationLinks"
            :key="link.name"
            :class="link.subLinks ? 'hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none]' : ''">
            <nuxt-link
              v-if="!link.subLinks.length"
              :to="link.href"
              class="nav-link"
              active-class="nav-link-active">
              {{ link.name }}
            </nuxt-link>
            <div
              v-else
              class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none] [--trigger:hover]">
              <nuxt-link
                :to="link.href"
                class="nav-link"
                active-class="nav-link-active">
                {{ link.name }}
                <ChevronDownIcon
                  v-if="link.subLinks.length"
                  class="h-5 w-5 text-light-gray" />
              </nuxt-link>
              <div class="hs-dropdown-menu transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 z-10 bg-white sm:shadow-md rounded-sm p-2 before:absolute top-full sm:border before:-top-5 before:left-0 before:w-full before:h-5 hidden">
                <nuxt-link
                  v-for="sublink in link.subLinks"
                  :key="sublink.name"
                  :to="sublink.href"
                  class="nav-sublink">
                  {{ sublink.name }}
                </nuxt-link>
              </div>
            </div>
          </span>
        </div>
      </div>
    </nav>
  </header>
  <div class="h-6 w-full bg-primary-yellow" />
</template>

<script lang="ts" setup>
  import { ChevronDownIcon } from '@heroicons/vue/24/solid';
  import { navigationLinks } from '@/helpers/data';
  import IconLogo from '@/assets/images/logo_white.svg';
</script>
```

I am using [Preline UI](https://preline.co/docs/collapse.html), which uses what might be classes unique to Preline such as `[--trigger:hover]` or `[--strategy:static]`.

**Comment by abdul-alhasany** [comment]
Thanks.

It is is fixed now. You can upgrade the plugin.

**Comment by jimmiejackson414** [comment]
Fantastic, that seems to have worked. Thanks so much for the quick fix!

**Comment by abdul-alhasany** [comment]
No problem.
